In [2]:
import torch
import numpy as np
torch.__version__

'2.2.1+cu118'

In [8]:
x_torch = torch.arange(1.0,10.0)  #tensor
print(x_torch)
x_torch.dtype

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


torch.float32

In [11]:
x_array = np.arange(1.0,11.0)  #array
print(x_array)
x_array.dtype

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


dtype('float64')

In [13]:
conv_torch = x_torch.numpy()  #change tensor to arry
print(conv_torch)
conv_torch.dtype  #keeps tensors dtype even as array

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


dtype('float32')

In [14]:
conv_arr = torch.from_numpy(x_array) #change array to tensor
print(conv_arr)
conv_arr.dtype #keeps array dtype even as tensor

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)


torch.float64